
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - garo.tietoevry.com
  resources:
  - githubactionrunners
  verbs:
  - '*'
- apiGroups:
  - garo.tietoevry.com
  resources:
  - githubactionrunners/finalizers
  verbs:
  - update
- apiGroups:
  - garo.tietoevry.com
  resources:
  - githubactionrunners/status
  verbs:
  - get
  - patch
  - update
