//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubActionRunner) DeepCopyInto(out *GithubActionRunner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubActionRunner.
func (in *GithubActionRunner) DeepCopy() *GithubActionRunner {
	if in == nil {
		return nil
	}
	out := new(GithubActionRunner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GithubActionRunner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubActionRunnerList) DeepCopyInto(out *GithubActionRunnerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GithubActionRunner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubActionRunnerList.
func (in *GithubActionRunnerList) DeepCopy() *GithubActionRunnerList {
	if in == nil {
		return nil
	}
	out := new(GithubActionRunnerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GithubActionRunnerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubActionRunnerSpec) DeepCopyInto(out *GithubActionRunnerSpec) {
	*out = *in
	out.MinTTL = in.MinTTL
	in.PodTemplateSpec.DeepCopyInto(&out.PodTemplateSpec)
	in.TokenRef.DeepCopyInto(&out.TokenRef)
	out.ReconciliationPeriod = in.ReconciliationPeriod
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubActionRunnerSpec.
func (in *GithubActionRunnerSpec) DeepCopy() *GithubActionRunnerSpec {
	if in == nil {
		return nil
	}
	out := new(GithubActionRunnerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubActionRunnerStatus) DeepCopyInto(out *GithubActionRunnerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubActionRunnerStatus.
func (in *GithubActionRunnerStatus) DeepCopy() *GithubActionRunnerStatus {
	if in == nil {
		return nil
	}
	out := new(GithubActionRunnerStatus)
	in.DeepCopyInto(out)
	return out
}
