// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubActionRunner) DeepCopyInto(out *GithubActionRunner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubActionRunner.
func (in *GithubActionRunner) DeepCopy() *GithubActionRunner {
	if in == nil {
		return nil
	}
	out := new(GithubActionRunner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GithubActionRunner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubActionRunnerList) DeepCopyInto(out *GithubActionRunnerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GithubActionRunner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubActionRunnerList.
func (in *GithubActionRunnerList) DeepCopy() *GithubActionRunnerList {
	if in == nil {
		return nil
	}
	out := new(GithubActionRunnerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GithubActionRunnerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubActionRunnerSpec) DeepCopyInto(out *GithubActionRunnerSpec) {
	*out = *in
	in.PodSpec.DeepCopyInto(&out.PodSpec)
	in.TokenRef.DeepCopyInto(&out.TokenRef)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubActionRunnerSpec.
func (in *GithubActionRunnerSpec) DeepCopy() *GithubActionRunnerSpec {
	if in == nil {
		return nil
	}
	out := new(GithubActionRunnerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubActionRunnerStatus) DeepCopyInto(out *GithubActionRunnerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubActionRunnerStatus.
func (in *GithubActionRunnerStatus) DeepCopy() *GithubActionRunnerStatus {
	if in == nil {
		return nil
	}
	out := new(GithubActionRunnerStatus)
	in.DeepCopyInto(out)
	return out
}
